### ISSUE TITLE
ElectricSpock is not compatible with Robolectric 3.4.x

### ISSUE THREAD

**Issue by bartek-wesolowski** [hkhc/electricspock#3]
It would be great if ElectricSpock supported the latest version of Robolectric, because it fixes a lot of issues. Right now there's a method in ElectricSputnik.java checking the Robolectric version and failing if it's not 3.3.x. Perhaps removing this check would be enough.

**Comment by hkhc** [comment]
HI. Just released version 0.6. Should be OK with 3.4.2.

**Comment by autonomousapps** [comment]
I still get this error:
```
java.lang.RuntimeException: This version of ElectricSpock supports Robolectric 3.3 or 3.4 only
```
I am adding your project like this:
```
testCompile 'com.github.hkhc:electricspock:0.6'
```

Update: I debugged, and it reported I was using Robolectric 3.0. I haven't removed Robospock from my dependencies yet, so that is probably what's causing it.

Second update: I suggest your error log state which version is currently being used.

**Comment by hkhc** [comment]
>  I suggest your error log state which version is currently being used.

Good idea. will do that.

**Comment by autonomousapps** [comment]
WOW. What a huge pain. In case this helps anyone else migrating from RoboSpock, I had terrible gradle caching issues. I cleaned the project, I invalidated caches, I even manually deleted my project's `build/` and `.gradle/` directories. I ultimately also deleted `~/.gradle/caches` and `~/.gradle/daemon`. That finally did it.
